# Only run this pipeline when it's scheduled from the web interface
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

# Pull submodule content
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Include template
include:
  - project: 'infrastructure/gitlab-ci'
    file: '.gitlab-ci.deploy-python.yml'

# Run template job
install-python-app:
  tags:
    - targetspot
    - prd
  variables:
    VAULT_TOKEN: $VAULT_TOKEN_PRD
    VAULT_URL: $VAULT_URL_PRD
    SRV_LIST: "ppiq-cw-api-1.aws.targetspot.com"
    SVC_USER: "ppiq"
    PROJECT_NAME: "contextual_web_api"
  extends:
    - .deploy_python
  before_script:
    - |
      DIR_PATH="/home/runner/transformers"
      if [ -d "${DIR_PATH}" ] && [ ! -h "${DIR_PATH}" ]; then
        exit
      else
        git clone https://github.com/huggingface/transformers "${DIR_PATH}"
        cd "${DIR_PATH}" && pip install .
      fi