variables:
  SRV_LIST: "ppiq-cw-api-1.aws.targetspot.com"
  SVC_USER: "ppiq"
  PROJECT_NAME: "contextual_web_api"

# Only run this pipeline when it's scheduled from the web interface
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

include: 
 - local: '.gitlab/template-deploy-python.yml'