# Only run this pipeline when it's scheduled from the web interface
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

# Pull submodule content
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Include template
include: 
  - project: 'infrastructure/gitlab-ci'
    file: 'template-deploy-python.yml'

# Run temaplate job
job:
  variables:
    SRV_LIST: "ppiq-cw-api-1.aws.targetspot.com"
    SVC_USER: "ppiq"
    PROJECT_NAME: "contextual_web_api"
  extends:
    - deploy_python